BIN = $(PWD)/node_modules/.bin

LEZER_ARGS :=
ifdef DEBUG
	LEZER_ARGS := --names $(LEZER_ARGS)
endif

# Written by humans
SRC = src/julia.grammar src/tokens.js

# Generated by lezer
PARSER = src/_parser.js src/_parser.terms.js

# Bundled by rollup
INDEX = dist/index.cjs dist/index.es.js


.DELETE_ON_ERROR:

build: $(INDEX)

$(INDEX): $(PARSER)
	ROLLUP_IN="$(<)" \
	ROLLUP_OUT="dist/index" \
	$(BIN)/rollup -c

# If the parser generation fails, you might need to set the following environment variable:
# export NODE_OPTIONS="--max-old-space-size=8192"
$(PARSER): $(SRC)
	$(BIN)/lezer-generator $(LEZER_ARGS) $(<) -o src/_parser


.PHONY: test check clean

test: $(PARSER) test/*
	$(BIN)/mocha test/test-julia.js

check: # Ensure tooling is installed
	node --version
	npm --version

clean: # Remove generated files
	rm $(PARSER)
	rm $(INDEX)
